<a href="https://colab.research.google.com/github/Sunstreaker/227-ML/blob/main/Group227_Heartattack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

url = "https://raw.githubusercontent.com/Sunstreaker/227-ML/main/heart.csv"

heart_data = pd.read_csv(url);

heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [22]:
heart_data.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [24]:
heart_data.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [50]:

heart_data.drop_duplicates(inplace=True)

heart_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,302.00000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000
mean,54.42053,0.682119,0.963576,131.602649,246.500000,0.149007,0.526490,149.569536,0.327815,1.043046,1.397351,0.718543,2.314570,0.543046
std,9.04797,0.466426,1.032044,17.563394,51.753489,0.356686,0.526027,22.903527,0.470196,1.161452,0.616274,1.006748,0.613026,0.498970
min,29.00000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.00000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.250000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.50000,1.000000,1.000000,130.000000,240.500000,0.000000,1.000000,152.500000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.00000,1.000000,2.000000,140.000000,274.750000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.00000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

Separate the features (X) and the target variable (y):

In [29]:
x = heart_data.drop('target', axis=1)
y = heart_data['target']

In [30]:
x.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000

In [31]:
y.describe()

count    303.000000
mean       0.544554
std        0.498835
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: target, dtype: float64

Split the dataset into training and testing sets:

In [65]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [34]:
X_train.count()

age         242
sex         242
cp          242
trestbps    242
chol        242
fbs         242
restecg     242
thalach     242
exang       242
oldpeak     242
slope       242
ca          242
thal        242
dtype: int64

In [35]:
X_test.count()

age         61
sex         61
cp          61
trestbps    61
chol        61
fbs         61
restecg     61
thalach     61
exang       61
oldpeak     61
slope       61
ca          61
thal        61
dtype: int64

Perform feature scaling on the numerical features:

In [66]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Train a Random Forest Classifier:

In [67]:
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=42)

Predict the target variable for the test set:

In [68]:
y_pred = clf.predict(X_test_scaled)

Evaluate the model's performance:

In [69]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8360655737704918

# possibility of age greater than 50

In [78]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

url = "https://raw.githubusercontent.com/Sunstreaker/227-ML/main/heart.csv"

heart_data = pd.read_csv(url);

heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [100]:

X = heart_data.drop('target', axis=1)
y = heart_data['target']

selected_data = heart_data[heart_data['age'] > 50].drop('target', axis=1)

selected_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,59.375000,0.668269,0.918269,134.802885,252.846154,0.187500,0.490385,144.552885,0.375000,1.210096,1.341346,0.889423,2.346154
std,5.603118,0.471971,1.062334,18.541104,54.382572,0.391254,0.538296,22.511985,0.485291,1.204558,0.616850,1.017852,0.655990
min,51.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,55.000000,0.000000,0.000000,121.500000,215.500000,0.000000,0.000000,130.000000,0.000000,0.100000,1.000000,0.000000,2.000000
50%,58.500000,1.000000,0.000000,132.000000,246.000000,0.000000,0.000000,147.500000,0.000000,1.000000,1.000000,1.000000,2.000000
75%,63.000000,1.000000,2.000000,145.000000,283.000000,0.000000,1.000000,161.000000,1.000000,1.825000,2.000000,2.000000,3.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,195.000000,1.000000,6.200000,2.000000,4.000000,3.000000

using RandomForestClassifier to train a machine learning model

In [101]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

# Predict the heart attack possibility for individuals with age > 50 and print it

In [104]:
selected_data_scaled = scaler.transform(selected_data)
predictions = clf.predict(selected_data_scaled)
for i, prediction in enumerate(predictions):
    print(f"Individual {i+1}: Heart Attack Possibility = {prediction}")

Individual 1: Heart Attack Possibility = 1
Individual 2: Heart Attack Possibility = 1
Individual 3: Heart Attack Possibility = 1
Individual 4: Heart Attack Possibility = 1
Individual 5: Heart Attack Possibility = 1
Individual 6: Heart Attack Possibility = 1
Individual 7: Heart Attack Possibility = 1
Individual 8: Heart Attack Possibility = 1
Individual 9: Heart Attack Possibility = 1
Individual 10: Heart Attack Possibility = 1
Individual 11: Heart Attack Possibility = 1
Individual 12: Heart Attack Possibility = 1
Individual 13: Heart Attack Possibility = 1
Individual 14: Heart Attack Possibility = 1
Individual 15: Heart Attack Possibility = 1
Individual 16: Heart Attack Possibility = 0
Individual 17: Heart Attack Possibility = 1
Individual 18: Heart Attack Possibility = 1
Individual 19: Heart Attack Possibility = 1
Individual 20: Heart Attack Possibility = 1
Individual 21: Heart Attack Possibility = 1
Individual 22: Heart Attack Possibility = 1
Individual 23: Heart Attack Possibility = 1
Individual 24: Heart Attack Possibility = 1
Individual 25: Heart Attack Possibility = 1
Individual 26: Heart Attack Possibility = 1
Individual 27: Heart Attack Possibility = 1
Individual 28: Heart Attack Possibility = 1
Individual 29: Heart Attack Possibility = 1
Individual 30: Heart Attack Possibility = 1
Individual 31: Heart Attack Possibility = 1
Individual 32: Heart Attack Possibility = 1
Individual 33: Heart Attack Possibility = 1
Individual 34: Heart Attack Possibility = 1
Individual 35: Heart Attack Possibility = 0
Individual 36: Heart Attack Possibility = 1
Individual 37: Heart Attack Possibility = 1
Individual 38: Heart Attack Possibility = 1
Individual 39: Heart Attack Possibility = 1
Individual 40: Heart Attack Possibility = 1
Individual 41: Heart Attack Possibility = 1
Individual 42: Heart Attack Possibility = 1
Individual 43: Heart Attack Possibility = 1
Individual 44: Heart Attack Possibility = 1
Individual 45: Heart Attack Possibility = 1
Individual 46: Heart Attack Possibility = 1
Individual 47: Heart Attack Possibility = 1
Individual 48: Heart Attack Possibility = 1
Individual 49: Heart Attack Possibility = 1
Individual 50: Heart Attack Possibility = 1
Individual 51: Heart Attack Possibility = 1
Individual 52: Heart Attack Possibility = 1
Individual 53: Heart Attack Possibility = 1
Individual 54: Heart Attack Possibility = 1
Individual 55: Heart Attack Possibility = 1
Individual 56: Heart Attack Possibility = 1
Individual 57: Heart Attack Possibility = 1
Individual 58: Heart Attack Possibility = 1
Individual 59: Heart Attack Possibility = 1
Individual 60: Heart Attack Possibility = 0
Individual 61: Heart Attack Possibility = 1
Individual 62: Heart Attack Possibility = 1
Individual 63: Heart Attack Possibility = 1
Individual 64: Heart Attack Possibility = 0
Individual 65: Heart Attack Possibility = 0
Individual 66: Heart Attack Possibility = 1
Individual 67: Heart Attack Possibility = 0
Individual 68: Heart Attack Possibility = 1
Individual 69: Heart Attack Possibility = 1
Individual 70: Heart Attack Possibility = 1
Individual 71: Heart Attack Possibility = 1
Individual 72: Heart Attack Possibility = 1
Individual 73: Heart Attack Possibility = 1
Individual 74: Heart Attack Possibility = 1
Individual 75: Heart Attack Possibility = 0
Individual 76: Heart Attack Possibility = 1
Individual 77: Heart Attack Possibility = 1
Individual 78: Heart Attack Possibility = 1
Individual 79: Heart Attack Possibility = 1
Individual 80: Heart Attack Possibility = 1
Individual 81: Heart Attack Possibility = 1
Individual 82: Heart Attack Possibility = 1
Individual 83: Heart Attack Possibility = 1
Individual 84: Heart Attack Possibility = 1
Individual 85: Heart Attack Possibility = 1
Individual 86: Heart Attack Possibility = 1
Individual 87: Heart Attack Possibility = 0
Individual 88: Heart Attack Possibility = 1
Individual 89: Heart Attack Possibility = 1
Individual 90: Heart Attack Possibility = 1
Individual 91: Heart Attack Possibility = 1
Individual 92: Heart Attack Possibility = 1
Individual 93: Heart Attack Possibility = 1
Individual 94: Heart Attack Possibility = 1
Individual 95: Heart Attack Possibility = 1
Individual 96: Heart Attack Possibility = 0
Individual 97: Heart Attack Possibility = 1
Individual 98: Heart Attack Possibility = 1
Individual 99: Heart Attack Possibility = 1
Individual 100: Heart Attack Possibility = 0
Individual 101: Heart Attack Possibility = 0
Individual 102: Heart Attack Possibility = 0
Individual 103: Heart Attack Possibility = 1
Individual 104: Heart Attack Possibility = 0
Individual 105: Heart Attack Possibility = 1
Individual 106: Heart Attack Possibility = 1
Individual 107: Heart Attack Possibility = 0
Individual 108: Heart Attack Possibility = 0
Individual 109: Heart Attack Possibility = 0
Individual 110: Heart Attack Possibility = 1
Individual 111: Heart Attack Possibility = 1
Individual 112: Heart Attack Possibility = 1
Individual 113: Heart Attack Possibility = 0
Individual 114: Heart Attack Possibility = 1
Individual 115: Heart Attack Possibility = 1
Individual 116: Heart Attack Possibility = 1
Individual 117: Heart Attack Possibility = 0
Individual 118: Heart Attack Possibility = 1
Individual 119: Heart Attack Possibility = 0
Individual 120: Heart Attack Possibility = 1
Individual 121: Heart Attack Possibility = 0
Individual 122: Heart Attack Possibility = 1
Individual 123: Heart Attack Possibility = 0
Individual 124: Heart Attack Possibility = 0
Individual 125: Heart Attack Possibility = 0
Individual 126: Heart Attack Possibility = 0
Individual 127: Heart Attack Possibility = 0
Individual 128: Heart Attack Possibility = 1
Individual 129: Heart Attack Possibility = 1
Individual 130: Heart Attack Possibility = 0
Individual 131: Heart Attack Possibility = 1
Individual 132: Heart Attack Possibility = 1
Individual 133: Heart Attack Possibility = 0
Individual 134: Heart Attack Possibility = 1
Individual 135: Heart Attack Possibility = 1
Individual 136: Heart Attack Possibility = 0
Individual 137: Heart Attack Possibility = 1
Individual 138: Heart Attack Possibility = 1
Individual 139: Heart Attack Possibility = 1
Individual 140: Heart Attack Possibility = 0
Individual 141: Heart Attack Possibility = 1
Individual 142: Heart Attack Possibility = 0
Individual 143: Heart Attack Possibility = 0
Individual 144: Heart Attack Possibility = 1
Individual 145: Heart Attack Possibility = 0
Individual 146: Heart Attack Possibility = 0
Individual 147: Heart Attack Possibility = 0
Individual 148: Heart Attack Possibility = 1
Individual 149: Heart Attack Possibility = 1
Individual 150: Heart Attack Possibility = 1
Individual 151: Heart Attack Possibility = 0
Individual 152: Heart Attack Possibility = 1
Individual 153: Heart Attack Possibility = 0
Individual 154: Heart Attack Possibility = 0
Individual 155: Heart Attack Possibility = 1
Individual 156: Heart Attack Possibility = 0
Individual 157: Heart Attack Possibility = 0
Individual 158: Heart Attack Possibility = 0
Individual 159: Heart Attack Possibility = 1
Individual 160: Heart Attack Possibility = 1
Individual 161: Heart Attack Possibility = 0
Individual 162: Heart Attack Possibility = 1
Individual 163: Heart Attack Possibility = 0
Individual 164: Heart Attack Possibility = 0
Individual 165: Heart Attack Possibility = 0
Individual 166: Heart Attack Possibility = 1
Individual 167: Heart Attack Possibility = 0
Individual 168: Heart Attack Possibility = 0
Individual 169: Heart Attack Possibility = 0
Individual 170: Heart Attack Possibility = 0
Individual 171: Heart Attack Possibility = 1
Individual 172: Heart Attack Possibility = 0
Individual 173: Heart Attack Possibility = 1
Individual 174: Heart Attack Possibility = 0
Individual 175: Heart Attack Possibility = 1
Individual 176: Heart Attack Possibility = 0
Individual 177: Heart Attack Possibility = 0
Individual 178: Heart Attack Possibility = 1
Individual 179: Heart Attack Possibility = 1
Individual 180: Heart Attack Possibility = 0
Individual 181: Heart Attack Possibility = 0
Individual 182: Heart Attack Possibility = 1
Individual 183: Heart Attack Possibility = 0
Individual 184: Heart Attack Possibility = 1
Individual 185: Heart Attack Possibility = 1
Individual 186: Heart Attack Possibility = 0
Individual 187: Heart Attack Possibility = 1
Individual 188: Heart Attack Possibility = 1
Individual 189: Heart Attack Possibility = 0
Individual 190: Heart Attack Possibility = 0
Individual 191: Heart Attack Possibility = 1
Individual 192: Heart Attack Possibility = 1
Individual 193: Heart Attack Possibility = 0
Individual 194: Heart Attack Possibility = 1
Individual 195: Heart Attack Possibility = 1
Individual 196: Heart Attack Possibility = 0
Individual 197: Heart Attack Possibility = 1
Individual 198: Heart Attack Possibility = 1
Individual 199: Heart Attack Possibility = 0
Individual 200: Heart Attack Possibility = 0
Individual 201: Heart Attack Possibility = 1
Individual 202: Heart Attack Possibility = 0
Individual 203: Heart Attack Possibility = 1
Individual 204: Heart Attack Possibility = 0
Individual 205: Heart Attack Possibility = 1
Individual 206: Heart Attack Possibility = 0
Individual 207: Heart Attack Possibility = 1
Individual 208: Heart Attack Possibility = 1

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

Individual 1: Heart Attack Possibility = 1
Individual 2: Heart Attack Possibility = 1
Individual 3: Heart Attack Possibility = 1
Individual 4: Heart Attack Possibility = 1
Individual 5: Heart Attack Possibility = 1
Individual 6: Heart Attack Possibility = 1
Individual 7: Heart Attack Possibility = 1
Individual 8: Heart Attack Possibility = 1
Individual 9: Heart Attack Possibility = 1
Individual 10: Heart Attack Possibility = 1
Individual 11: Heart Attack Possibility = 1
Individual 12: Heart Attack Possibility = 1
Individual 13: Heart Attack Possibility = 1
Individual 14: Heart Attack Possibility = 1
Individual 15: Heart Attack Possibility = 1
Individual 16: Heart Attack Possibility = 0
Individual 17: Heart Attack Possibility = 1
Individual 18: Heart Attack Possibility = 1
Individual 19: Heart Attack Possibility = 1
Individual 20: Heart Attack Possibility = 1
Individual 21: Heart Attack Possibility = 1
Individual 22: Heart Attack Possibility = 1
Individual 23: Heart Attack Possibility = 1
Individual 24: Heart Attack Possibility = 1
Individual 25: Heart Attack Possibility = 1
Individual 26: Heart Attack Possibility = 1
Individual 27: Heart Attack Possibility = 1
Individual 28: Heart Attack Possibility = 1
Individual 29: Heart Attack Possibility = 1
Individual 30: Heart Attack Possibility = 1
Individual 31: Heart Attack Possibility = 1
Individual 32: Heart Attack Possibility = 1
Individual 33: Heart Attack Possibility = 1
Individual 34: Heart Attack Possibility = 1
Individual 35: Heart Attack Possibility = 0
Individual 36: Heart Attack Possibility = 1
Individual 37: Heart Attack Possibility = 1
Individual 38: Heart Attack Possibility = 1
Individual 39: Heart Attack Possibility = 1
Individual 40: Heart Attack Possibility = 1
Individual 41: Heart Attack Possibility = 1
Individual 42: Heart Attack Possibility = 1
Individual 43: Heart Attack Possibility = 1
Individual 44: Heart Attack Possibility = 1
Individual 45: Heart Attack Possibility = 1
Individual 46: Heart Attack Possibility = 1
Individual 47: Heart Attack Possibility = 1
Individual 48: Heart Attack Possibility = 1
Individual 49: Heart Attack Possibility = 1
Individual 50: Heart Attack Possibility = 1
Individual 51: Heart Attack Possibility = 1
Individual 52: Heart Attack Possibility = 1
Individual 53: Heart Attack Possibility = 1
Individual 54: Heart Attack Possibility = 1
Individual 55: Heart Attack Possibility = 1
Individual 56: Heart Attack Possibility = 1
Individual 57: Heart Attack Possibility = 1
Individual 58: Heart Attack Possibility = 1
Individual 59: Heart Attack Possibility = 1
Individual 60: Heart Attack Possibility = 0
Individual 61: Heart Attack Possibility = 1
Individual 62: Heart Attack Possibility = 1
Individual 63: Heart Attack Possibility = 1
Individual 64: Heart Attack Possibility = 0
Individual 65: Heart Attack Possibility = 0
Individual 66: Heart Attack Possibility = 1
Individual 67: Heart Attack Possibility = 0
Individual 68: Heart Attack Possibility = 1
Individual 69: Heart Attack Possibility = 1
Individual 70: Heart Attack Possibility = 1
Individual 71: Heart Attack Possibility = 1
Individual 72: Heart Attack Possibility = 1
Individual 73: Heart Attack Possibility = 1
Individual 74: Heart Attack Possibility = 1
Individual 75: Heart Attack Possibility = 0
Individual 76: Heart Attack Possibility = 1
Individual 77: Heart Attack Possibility = 1
Individual 78: Heart Attack Possibility = 1
Individual 79: Heart Attack Possibility = 1
Individual 80: Heart Attack Possibility = 1
Individual 81: Heart Attack Possibility = 1
Individual 82: Heart Attack Possibility = 1
Individual 83: Heart Attack Possibility = 1
Individual 84: Heart Attack Possibility = 1
Individual 85: Heart Attack Possibility = 1
Individual 86: Heart Attack Possibility = 1
Individual 87: Heart Attack Possibility = 0
Individual 88: Heart Attack Possibility = 1
Individual 89: Heart Attack Possibility = 1
Individual 90: Heart Attack Possibility = 1
Individual 91: Heart Attack Possibility = 1
Individual 92: Heart Attack Possibility = 1
Individual 93: Heart Attack Possibility = 1
Individual 94: Heart Attack Possibility = 1
Individual 95: Heart Attack Possibility = 1
Individual 96: Heart Attack Possibility = 0
Individual 97: Heart Attack Possibility = 1
Individual 98: Heart Attack Possibility = 1
Individual 99: Heart Attack Possibility = 1
Individual 100: Heart Attack Possibility = 0
Individual 101: Heart Attack Possibility = 0
Individual 102: Heart Attack Possibility = 0
Individual 103: Heart Attack Possibility = 1
Individual 104: Heart Attack Possibility = 0
Individual 105: Heart Attack Possibility = 1
Individual 106: Heart Attack Possibility = 1
Individual 107: Heart Attack Possibility = 0
Individual 108: Heart Attack Possibility = 0
Individual 109: Heart Attack Possibility = 0
Individual 110: Heart Attack Possibility = 1
Individual 111: Heart Attack Possibility = 1
Individual 112: Heart Attack Possibility = 1
Individual 113: Heart Attack Possibility = 0
Individual 114: Heart Attack Possibility = 1
Individual 115: Heart Attack Possibility = 1
Individual 116: Heart Attack Possibility = 1
Individual 117: Heart Attack Possibility = 0
Individual 118: Heart Attack Possibility = 1
Individual 119: Heart Attack Possibility = 0
Individual 120: Heart Attack Possibility = 1
Individual 121: Heart Attack Possibility = 0
Individual 122: Heart Attack Possibility = 1
Individual 123: Heart Attack Possibility = 0
Individual 124: Heart Attack Possibility = 0
Individual 125: Heart Attack Possibility = 0
Individual 126: Heart Attack Possibility = 0
Individual 127: Heart Attack Possibility = 0
Individual 128: Heart Attack Possibility = 1
Individual 129: Heart Attack Possibility = 1
Individual 130: Heart Attack Possibility = 0
Individual 131: Heart Attack Possibility = 1
Individual 132: Heart Attack Possibility = 1
Individual 133: Heart Attack Possibility = 0
Individual 134: Heart Attack Possibility = 1
Individual 135: Heart Attack Possibility = 1
Individual 136: Heart Attack Possibility = 0
Individual 137: Heart Attack Possibility = 1
Individual 138: Heart Attack Possibility = 1
Individual 139: Heart Attack Possibility = 1
Individual 140: Heart Attack Possibility = 0
Individual 141: Heart Attack Possibility = 1
Individual 142: Heart Attack Possibility = 0
Individual 143: Heart Attack Possibility = 0
Individual 144: Heart Attack Possibility = 1
Individual 145: Heart Attack Possibility = 0
Individual 146: Heart Attack Possibility = 0
Individual 147: Heart Attack Possibility = 0
Individual 148: Heart Attack Possibility = 1
Individual 149: Heart Attack Possibility = 1
Individual 150: Heart Attack Possibility = 1
Individual 151: Heart Attack Possibility = 0
Individual 152: Heart Attack Possibility = 1
Individual 153: Heart Attack Possibility = 0
Individual 154: Heart Attack Possibility = 0
Individual 155: Heart Attack Possibility = 1
Individual 156: Heart Attack Possibility = 0
Individual 157: Heart Attack Possibility = 0
Individual 158: Heart Attack Possibility = 0
Individual 159: Heart Attack Possibility = 1
Individual 160: Heart Attack Possibility = 1
Individual 161: Heart Attack Possibility = 0
Individual 162: Heart Attack Possibility = 1
Individual 163: Heart Attack Possibility = 0
Individual 164: Heart Attack Possibility = 0
Individual 165: Heart Attack Possibility = 0
Individual 166: Heart Attack Possibility = 1
Individual 167: Heart Attack Possibility = 0
Individual 168: Heart Attack Possibility = 0
Individual 169: Heart Attack Possibility = 0
Individual 170: Heart Attack Possibility = 0
Individual 171: Heart Attack Possibility = 1
Individual 172: Heart Attack Possibility = 0
Individual 173: Heart Attack Possibility = 1
Individual 174: Heart Attack Possibility = 0
Individual 175: Heart Attack Possibility = 1
Individual 176: Heart Attack Possibility = 0
Individual 177: Heart Attack Possibility = 0
Individual 178: Heart Attack Possibility = 1
Individual 179: Heart Attack Possibility = 1
Individual 180: Heart Attack Possibility = 0
Individual 181: Heart Attack Possibility = 0
Individual 182: Heart Attack Possibility = 1
Individual 183: Heart Attack Possibility = 0
Individual 184: Heart Attack Possibility = 1
Individual 185: Heart Attack Possibility = 1
Individual 186: Heart Attack Possibility = 0
Individual 187: Heart Attack Possibility = 1
Individual 188: Heart Attack Possibility = 1
Individual 189: Heart Attack Possibility = 0
Individual 190: Heart Attack Possibility = 0
Individual 191: Heart Attack Possibility = 1
Individual 192: Heart Attack Possibility = 1
Individual 193: Heart Attack Possibility = 0
Individual 194: Heart Attack Possibility = 1
Individual 195: Heart Attack Possibility = 1
Individual 196: Heart Attack Possibility = 0
Individual 197: Heart Attack Possibility = 1
Individual 198: Heart Attack Possibility = 1
Individual 199: Heart Attack Possibility = 0
Individual 200: Heart Attack Possibility = 0
Individual 201: Heart Attack Possibility = 1
Individual 202: Heart Attack Possibility = 0
Individual 203: Heart Attack Possibility = 1
Individual 204: Heart Attack Possibility = 0
Individual 205: Heart Attack Possibility = 1
Individual 206: Heart Attack Possibility = 0
Individual 207: Heart Attack Possibility = 1
Individual 208: Heart Attack Possibility = 1